apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api-dev-ns
spec:
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registrybnt1510.azurecr.io/tripinsights/trips:1.0
        imagePullPolicy: "Always"
        env:
          - name: SQL_USER
            value: sqladmingUx2831
          - name: SQL_PASSWORD
            value: oF1jz9Ti4
          - name: SQL_SERVER
            value: sqlservergux2831.database.windows.net
          - name: SQL_DBNAME
            value: mydrivingDB
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
  - port: 8080
    targetPort: 80
